[project]
name = "kanka-slurp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "tqdm>=4.68.1",
]

[tool.poetry.dependencies]
# Runtime dependencies for kanka-slurp
requests = "^2.28"
python-dotenv = "^1.0"
tqdm = "^4.0"
